### ISSUE TITLE
fec12 vs fec16

### ISSUE THREAD

**Issue by nicholasjhorton** [baumer-lab/fec12#4]
I love the package.  But it says fec16 and the hex sticker is also fec16.

**Comment by beanumber** [comment]
Yes, `fec16` is on its way to CRAN. There are no such plans for `fec12`.

**Comment by nicholasjhorton** [comment]
I find it confusing the fec12 mentions fec16 and the fec16 hex sticker.  
![Screen Shot 2020-08-25 at 8 50 48 AM](https://user-images.githubusercontent.com/530542/91176362-30779f80-e6b0-11ea-8a1f-ac2f08620285.png)

Just my $0.02, Nick

**Comment by beanumber** [comment]
@mariumtapal can you make a sticker for `fec12`?
