### ISSUE TITLE
packages in Depends? 

### ISSUE THREAD

**Issue by beanumber** [baumer-lab/fec12#5]
Why are `readr` and `dplyr` in Depends? @mariumtapal what is the justification for having them in Depends and not Imports?

**Comment by mariumtapal** [comment]
@beanumber I believe it is just something that I overlooked. Will send a PR. 

We could also move `dplyr` and `readr` into Suggests; if we use the `dplyr::` and the `readr::` format inside the `read_all_*` functions, like `usethis::use_zip()`, we won't have to call `@Import` `dplyr` and `readr`. 

Also, do you plan to get this on CRAN? There are some other smaller changes to do if so

**Comment by beanumber** [comment]
I don't plan to put this on CRAN, but if you want to, I suppose we could. Maintaining CRAN packages can become time consuming, so I certainly wouldn't want a package every four years!
